# Playbook for Docker Install and Run
#
---
- name: "AWS - Install docker"
  gather_facts: no
  hosts: tag_Name_Production_Environment
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3  
    ansible_user: ubuntu

  tasks:
  - name: Pull Docker Image
    docker_image:
      name: mikedzn/epam_dev
      state: present
      source: pull

  - name: Stop and remove existing Docker Container
    docker_image:
      name: mikedzn_website
      state: absent

  - name: Start a new container based on the latest image
    docker_container:
      name: mikedzn_website
      image: mikedzn/epam_dev:latest
      state: started
      recreate: yes
