# Playbook for Docker Install and Run
#
---
- name: "AWS - Install docker"
  gather_facts: no
  hosts: Dev_instance
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3  
    ansible_user: ubuntu

  tasks:
  - name: Stop and remove existing Docker Container
    docker_image:
      name: mikedzn_website
      state: absent

  - name: Pull Docker Image
    docker_image:
      name: mikedzn/epam_dev:latest
      state: present
      source: pull
      force_source: yes

  - name: Start a new container based on the latest image
    docker_container:
      name: mikedzn_website
      image: mikedzn/epam_dev:latest
      state: started
      recreate: yes
      exposed_ports: "80"
      ports: "80:80"

  - name: Clean up Docker images
    docker_prune:
      images: yes
      images_filters:
        dangling: false